id: P004341
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ41810
  title: དཔལ་ལྡན་ལྷ་མོར་བསྟོད་པ།
  author: ''
  volumes:
    33c462771771483aba3c6d475c3f0d71:
      image_group_id: I1KG18183
      title: ''
      volume_number: 1
      total_pages: 6
      base_file: v001.txt
